### PR TITLE
Replaced method of change release version

### PR DESCRIPTION
**Pull request by supermock**
Changed the method of pulling the version of the Meteor.

### CODE REVIEW

**Comment by Ulexus** [comment]
This doesn't appear to work, for me:

```
/tmp $ curl -s -d "release=1.4.4.1"  https://install.meteor.com |grep RELEASE
RELEASE="1.4.4.2"
TARBALL_URL="https://meteorinstall-4168.kxcdn.com/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz"
echo "Meteor ${RELEASE} has been installed in your home directory (~/.meteor)."
```

**Comment by supermock** [comment]
Sorry, I found the -d parameter of cURL to have effect = /

**Comment by Ulexus** [comment]
Aha, that _does_ work.  Thanks!

**Comment by supermock** [comment]
Your welcome!

**Pull request merged**
